name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-and-sonar-and-docker:
    runs-on: ubuntu-latest

    env:
      Solution_Name: ./Sources/OpenLibraryWS_Wrapper.sln
      Test_Project_Path: ./Sources/Tests
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run SonarQube Scanner
        run: dotnet sonarscanner begin /k:Dotnet_Dorian_HODIN /d:sonar.host.url="https://codefirst.iut.uca.fr/sonar/" /d:sonar.coverage.exclusions="./Sources/Tests/**" /d:sonar.login="$SONAR_TOKEN"
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

      - name: build
        run: |
          cd Sources
          dotnet restore OpenLibraryWS_Wrapper.sln
          dotnet build OpenLibraryWS_Wrapper.sln -c Release --no-restore

      - name: Execute unit tests
        run:
          dotnet test ./Sources/OpenLibraryWS_Wrapper.sln        

      - name: End SonarQube Analysis
        run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
  
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/openlibraryws_wrapper:latest -f ./Sources/Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/openlibraryws_wrapper:latest
      



